name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: submodules
      run: git submodule init && git submodule uptate
      
    - name: ghaction-cmake
      uses: lpenz/ghaction-cmake@v0.1
