name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - run: pip3 install numpy

    - run: python3 test/gen_test_files.py

    - env:
        CC: /usr/bin/gcc-9
        CXX: /usr/bin/g++-9
      run: cmake .

    - run: make -j $(nproc --all)

    - run: ctest
