name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - env:
        CC: /usr/bin/gcc-8
        CXX: /usr/bin/g++-8
      run: cmake .

    - run: make -j $(nproc --all)

    - run: make test
