name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - env:
        CC: /usr/bin/gcc-8
        CXX: /usr/bin/g++-8
      run: cmake -DNUMPYCPP_BUILD_TESTS=ON -DNUMPYCPP_USE_PYTHON3=ON -S . -B build

    - run: cmake --build build -j $(nproc --all)
    
    - run: ctest
      working-directory: build
