name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    runs-on: {{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - run: cmake -DNUMPYCPP_BUILD_TESTS=ON -DNUMPYCPP_USE_PYTHON3=ON -S . -B build

    - run: cmake --build build -j2
    
    - run: ctest
      working-directory: build
