# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.1

    # Runs a single command using the runners shell
    - name: build dir
      run: mkdir build && cd build

    # Runs a set of commands using the runners shell
    - name: cmake
      run: cmake ..
    
    - name: make
      run: make
    
    - name: test
      run: make test
